### ISSUE TITLE
Some comments and suggestions

### ISSUE THREAD

**Issue by Enchufa2** [rinze/obliterate_tweets#1]
- An option to keep some IDs would be lovely.
- I would move [these](https://github.com/rinze/obliterate_tweets/blob/master/delete_tweets.py#L9) options to `config.py` and I would use them in `delete_from_archive.py` too.
- Why [this sleep](https://github.com/rinze/obliterate_tweets/blob/master/delete_from_archive.py#L29)? From my experience, it runs well without this. And it takes A LOT of time, so I would remove it to save an hour per every ~3.5k tweets.
- Depending on the tweets to keep, `delete_tweets.py` may reach the rate limit imposed by Twitter. This can be handled easily [this way](http://tweepy.readthedocs.io/en/v3.5.0/code_snippet.html#handling-the-rate-limit-using-cursors).

**Comment by Enchufa2** [comment]
Oh, and I suppose you already know [this post](http://www.mathewinkson.com/2015/03/delete-old-tweets-selectively-using-python-and-tweepy). Just in case.

**Comment by rinze** [comment]
I'll re-implement the keep functionality as soon as I have some time. Perhaps the sleep time could be another variable to set up.

And yep, I know that post. It's one of the ones I read when I was looking for documentation and I took some ideas from it, but I've just realized I attributed it in a previous draft I had and not in this code. Corrected.

**Comment by rinze** [comment]
I don't have a Twitter account anymore and I don't think I'll work on this code in the short term. Closing for now :-)
